apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "waxuser"
            - name: POSTGRES_PASSWORD
              value: "waxuserpass"
            - name: POSTGRES_DB
              value: "atomic"
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            # Dynamic configuration environment variables (with defaults)
            - name: SHARED_BUFFERS_PERCENTAGE
              value: "25"
            - name: MAINTENANCE_WORK_MEM_PERCENTAGE
              value: "5"
            - name: EFFECTIVE_CACHE_SIZE_PERCENTAGE
              value: "50"
            - name: WORK_MEM_MULTIPLIER
              value: "256"
            - name: MAX_CONNECTIONS
              value: "100"
            - name: ENABLE_PG_TRGM
              value: "true"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - waxuser
                - -d
                - atomic
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - waxuser
                - -d
                - atomic
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgresql-pg-hba
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          command:
            - "postgres"
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
            - "-c"
            - "hba_file=/etc/postgresql/pg_hba.conf"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgresql-config
          configMap:
            name: postgresql-config
        - name: postgresql-pg-hba
          configMap:
            name: postgresql-pg-hba
        - name: init-script
          configMap:
            name: postgres-init-script
