apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-config-reader
  namespace: postgres
  labels:
    app: postgres
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-config-reader
  namespace: postgres
  labels:
    app: postgres
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
    resourceNames: ["postgresql-dynamic-config"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-config-reader
  namespace: postgres
  labels:
    app: postgres
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-config-reader
subjects:
  - kind: ServiceAccount
    name: postgres-config-reader
    namespace: postgres
