apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oneinacillian/docker_compose_autobuilds
    targetRevision: testapp
    path: k3s-deploy/hyperion-stack-deploy/rabbitmq-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 