FROM ubuntu:20.04
ARG ENVIRONMENT
RUN apt-get update && apt-get -y upgrade && apt-get -y install vim
WORKDIR /apps/wax
COPY ./node/$ENVIRONMENT/files .
#COPY ./snapshot ./snapshots
RUN apt-get install ./wax-leap-404wax01_4.0.4wax01-ubuntu-18.04_amd64.deb -y \
&& chmod +x start.sh \
&& chmod +x stop.sh