
version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes --supervised systemd --maxmemory 10gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    networks:
      - backend
    depends_on:
      - redis

  postgres:
    image: postgres:14
    container_name: postgresql
    tty: true
    environment:
      - POSTGRES_USER=waxuser
      - POSTGRES_PASSWORD=waxuserpass
      - POSTGRES_DB=atomic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./atomic/Deployment/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://waxuser:waxuserpass@postgres:5432/atomic?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - backend
    depends_on:
      - postgres

  atomic:
    container_name: atomic
    tty: true
    build:
      context: ./atomic/Deployment
      dockerfile: Dockerfile.atomic
      args:
        - ATOMIC_ENVIRONMENT=testnet
        - ATOMIC_LAUNCH_ON_STARTUP=false
        - SHIPHOST=172.168.40.50
        - HTTPHOST=172.168.40.50
        - SHIPPORT=29876
        - HTTPPORT=28888
        - POSTGRES_USER=waxuser
        - POSTGRES_PASSWORD=waxuserpass
        - POSTGRES_DB=atomic
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - atomic:/app/atomic
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/atomic/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/provisioning/atomic:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  redisdata:
  atomic:
  prometheus_data:
  grafana_data:
