{
 "title": "Basic Nodeos Dashboard",
 "tags": [
  "prometheus",
  "nodeos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "produced rounds",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(nodeos_producer_rounds[$__range])",
     "legendFormat": "{{producer}}"
    }
   ]
  },
  {
   "title": "headblocknum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nodeos_head_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "currentheadblocknum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodeos_head_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "irreversableblocknum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nodeos_last_irreversible_block_number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "currentirreversableblocknum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodeos_last_irreversible_block_number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "headblocktime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    { "expr": "nodeos_head_block_time * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "irreversibleblocktime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "nodeos_last_irreversible_block_time * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}