apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    # Memory settings
    indices.memory.index_buffer_size: 30%
    indices.fielddata.cache.size: 25%
    indices.queries.cache.size: 25%

    # Thread pool settings
    thread_pool:
      write:
        size: 4
        queue_size: 1000
      search:
        size: 12
        queue_size: 1000

    # Recovery settings
    indices.recovery.max_bytes_per_sec: 500mb
    indices.recovery.max_concurrent_file_chunks: 8

    # Cache settings
    cache.recycler.page.type: NONE

    # Disk settings
    cluster.routing.allocation.disk.threshold_enabled: false

    # HTTP settings
    http.max_content_length: 500mb 