apiVersion: apps/v1
kind: Deployment
metadata:
  name: es1
  labels:
    app: es1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es1
  template:
    metadata:
      labels:
        app: es1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: esdata1
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            runAsUser: 0
      containers:
        - name: es1
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: node.name
              value: "es1"
            - name: cluster.name
              value: "es-docker-cluster"
            - name: cluster.initial_master_nodes
              value: "es1"
            - name: discovery.seed_hosts
              value: "es1"
            - name: network.host
              value: "0.0.0.0"
            - name: network.publish_host
              value: "es1"
            - name: transport.host
              value: "0.0.0.0"
            - name: node.roles
              value: "[master, data, ingest, remote_cluster_client]"
            - name: ES_JAVA_OPTS
              value: "-Xms15g -Xmx15g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/elasticsearch"
            - name: ES_HEAP_DUMP_PATH
              value: "/var/log/elasticsearch"
            - name: ES_GC_LOG_PATH
              value: "/var/log/elasticsearch"
            - name: bootstrap.memory_lock
              value: "false"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.monitoring.collection.enabled
              value: "true"
          resources:
            limits:
              memory: "16Gi"
              cpu: "4"
            requests:
              memory: "16Gi"
              cpu: "2"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: esdata1
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: esdata1
          persistentVolumeClaim:
            claimName: es1-pvc
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config 