apiVersion: v1
kind: Service
metadata:
  name: es1
spec:
  type: ClusterIP
  selector:
    app: es1
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: transport 