apiVersion: v1
kind: Service
metadata:
  name: hyperion
spec:
  type: ClusterIP
  selector:
    app: hyperion
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: http
    - port: 1234
      targetPort: 1234
      protocol: TCP
      name: debug 