apiVersion: v1
kind: ConfigMap
metadata:
  name: atomic-config
  labels:
    app: atomic
data:
  # Main connections configuration
  connections.config.json: |
    {
      "postgres": {
        "host": "postgres",
        "port": 5432,
        "user": "waxuser",
        "password": "waxuserpass",
        "database": "atomic"
      },
      "redis": {
        "host": "redis",
        "port": 6379
      },
      "chain": {
        "name": "wax",
        "chain_id": "1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4",
        "http": "http://172.168.40.50:28888",
        "ship": "ws://172.168.40.50:29876"
      }
    }

  # Server configuration
  server.config.json: |
    {
      "provider_name": "oiac.io",
      "provider_url": "https://oiac.io",
      "server_addr": "0.0.0.0",
      "server_name": "atomic-test.oiac.io",
      "server_port": 9000,
      "cache_life": 5,
      "trust_proxy": true,
      "rate_limit": {
        "interval": 60,
        "requests": 240,
        "bill_execution_time": true
      },
      "ip_whitelist": [],
      "slow_query_threshold": 7500,
      "max_query_time_ms": 10000,
      "max_db_connections": 50,
      "metrics_port": 9010,
      "namespaces": [
        {
          "name": "atomicassets",
          "path": "/atomicassets",
          "args": {
            "atomicassets_account": "atomicassets",
            "connected_reader": "atomic-1",
            "socket_features": {
              "asset_update": false
            }
          }
        }
      ]
    }

  # Reader configuration
  readers.config.json: |
    [
      {
        "name": "atomic-1",
        "server_addr": "0.0.0.0",
        "server_port": 9001,
        "start_block": 64000000,
        "stop_block": 0,
        "irreversible_only": false,
        "ship_prefetch_blocks": 50,
        "ship_min_block_confirmation": 30,
        "ship_ds_queue_size": 20,
        "db_group_blocks": 10,
        "ds_ship_threads": 4,
        "modules": [],
        "contracts": [
          {
            "handler": "atomicassets",
            "args": {
              "atomicassets_account": "atomicassets",
              "store_transfers": true,
              "store_logs": true
            }
          }
        ]
      }
    ]

  # PM2 ecosystem configuration
  ecosystems.config.json: |
    {
      "apps": [
        {
          "name": "eosio-contract-api-filler",
          "script": "dist/filler.js",
          "instances": 1,
          "exec_mode": "fork",
          "env": {
            "NODE_ENV": "production",
            "NODE_OPTIONS": "--max-old-space-size=4096"
          },
          "error_file": "/app/logs/filler-error.log",
          "out_file": "/app/logs/filler-out.log",
          "log_file": "/app/logs/filler-combined.log",
          "time": true
        }
      ]
    }
