apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oneinacillian/hyperion-k8s
    targetRevision: testapp
    path: gateway-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 