global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics

  - job_name: postgresql
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  